# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'work_1_12' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for work_1_12
  pod 'SVProgressHUD'
end
